### ISSUE TITLE
您好,WWDC2018中文字幕已出,不知道您这个项目有计划抓取或更新吗?

### ISSUE THREAD

**Issue by TeWuJia** [kingcos/WWDCHelper#10]
感谢!

**Comment by kingcos** [comment]
首先，感谢关注哈！

这个已经提上日程，本来考虑是等待 Swift 5（结果跳票成 4.2）出来之后一起做适配，不过既然您已经提出来了，我将考虑尽快更新！届时更新后我再关闭该 Issue。

再次感谢关注！

**Comment by kingcos** [comment]
更新计划：

- 目前已完成对 WWDC 2014 - 2018 基本信息全兼容，但由于官方下载地址变动，之后将对下载字幕部分等更新，预计本周之内完成。

感谢您的关注！

---

Update plan:

- WWDCHelper supports to fetch WWDC basic info from 2014 to 2018. In this week, I will try to fix the function of downloading subtitles and etc.

Thanks for your attention!

**Comment by TeWuJia** [comment]
您好,我在使用脚本命令行下载wwdc2018的字幕会发生如下错误,然后会中断下载,下载汉语字幕会出现,英文字幕不会出现:
![image](https://user-images.githubusercontent.com/22377935/44566077-15f74c80-a79e-11e8-9c15-9f3b8c4a88f1.png)

**Comment by kingcos** [comment]
@TeWuJia 感谢反馈！

周末有空我会排查一下这个错误，再次感谢！

**Comment by MourinhoLove** [comment]
现在Release页面2018 WWDC还没有中文呀。不过已经有英文和日文了.

**Comment by kingcos** [comment]
> 现在Release页面2018 WWDC还没有中文呀。不过已经有英文和日文了.

感谢提醒，刚刚已经添加上了哈！

**Comment by kingcos** [comment]
@MourinhoLove 
感谢提醒，WWDC 2018 中文字幕已经添加，您现在可以再看一下。再次感谢！

**Comment by kingcos** [comment]
为什么回复不见了呢。。。

**Comment by kingcos** [comment]
@TeWuJia 忘记回复您了，实在抱歉。我目前查到的原因是 Apple 某些视频的 m3u8 链接会直接重定向到 WWDC 的主页，而非展示 fileSequence 的页面，所以脚本在获取时无法得到正确的 fileSequence 数量，进而报错。
修复的方法是我设置了默认的 100，即使该页面无法获取，也会尝试搜索字幕，之后根据 WEBVTT 字幕判断，再进行拼接。
您可以再尝试下，如果有问题可以继续回复并打开 Issue，多谢您的提问和关注！

**Comment by MourinhoLove** [comment]
> > 现在Release页面2018 WWDC还没有中文呀。不过已经有英文和日文了.
> 
> @MourinhoLove 感谢提醒，刚刚已经添加上了哈！

好的，谢谢，看到了。
