### ISSUE TITLE
字幕重复

### ISSUE THREAD

**Issue by wzshare** [kingcos/WWDCHelper#13]
当一条字幕跨越整数分钟时会出现重复
比如
> 18
> 00:00:59,096 --> 00:01:00,406
> 视图之间的关系
> 
> 19
> 00:00:59,096 --> 00:01:00,406
> 视图之间的关系

**Comment by kingcos** [comment]
感谢您提出！

这个我会去排查一下是官方字幕问题还是我在拼接时出现的问题。

**Comment by kingcos** [comment]
@wzshare 很抱歉，刚刚才有空查明。这个是因为 Apple 官方的字幕每个 fileSequence 都会在开头重复上一条的末尾，拼接的时候并没有处理是因为这样并不会影响播放器（已在 IINA v1.0.0-beta 3  测试）的加载，您的播放器加载时会有问题吗？

**Comment by wzshare** [comment]
VLC for Mac v2.2.4 和 VLC for iPhone 会重复字幕。
测试了iPhone端，QQ 影音和 AVPlayer 不会重复，KMPlayer 会重复。看来确实是播放器处理逻辑差异。
