### ISSUE TITLE
download fail

### ISSUE THREAD

**Issue by iwming** [kingcos/WWDCHelper#18]
Unknown Error: Error Domain=NSCocoaErrorDomain Code=518 "The file couldn’t be saved because the specified URL type isn’t supported." UserInfo={NSURL=410_hd_creating_custom_instruments.zho.srt}

**Comment by kingcos** [comment]
感谢反馈！

您能把执行出错的原始的命令补充一下吗？

**Comment by kingcos** [comment]
由于该问题暂未复现，且未补充，目前暂做关闭处理，如有问题欢迎再次 Open，感谢提出问题～

**Comment by yanqizhao** [comment]
我遇到了同样的问题耶，就是执行示例的代码出现的
![截屏2021-01-20 10 48 30](https://user-images.githubusercontent.com/16577092/105120482-45e0e080-5b0d-11eb-889a-fbf5596863bd.png)
