### ISSUE TITLE
WWDC 2019什么时候支持一下呢?

### ISSUE THREAD

**Issue by Link913** [kingcos/WWDCHelper#19]

**Comment by kingcos** [comment]
感谢关注！实在抱歉没有实时更新，我会争取在这个周末支持一下～

**Comment by Link913** [comment]
辛苦了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: kingcos <notifications@github.com>
发送时间: Thursday, August 15, 2019 3:37:07 PM
收件人: kingcos/WWDCHelper <WWDCHelper@noreply.github.com>
抄送: Link <fanyang_32012@outlook.com>; Author <author@noreply.github.com>
主题: Re: [kingcos/WWDCHelper] WWDC 2019什么时候支持一下呢? (#19)


感谢关注！实在抱歉没有实时更新，我会争取在这个周末支持一下～

―

**Comment by kingcos** [comment]
非常感谢提出问题。对于 Issue 我先 Reopen 哈，待真正解决后再关闭 😊。

**Comment by RavenKite** [comment]
> 非常感谢提出问题。对于 Issue 我先 Reopen 哈，待真正解决后再关闭 😊。

大佬，WWDC 2019更新中文字幕啦，求支持一下吧~！😊🙏

**Comment by kingcos** [comment]
@RavenKite 感谢关注！正在支持，尽情期待～

**Comment by kingcos** [comment]
@Link913 
@RavenKite 

感谢两位关注，目前 WWDC 2019 中文版和英文版字幕已经更新到：[Release v1.0.1](https://github.com/kingcos/WWDCHelper/releases/tag/v1.0.1)。

*需要注意的是 601 和 820 的中文字幕似乎 Apple 官方出现了问题，即使在官方也无法看到中文，因此这两个 Session 不包含在中文版中。*

欢迎下载、试用，有任何问题都可以再向我提出 Issue，非常感谢！

**Comment by Link913** [comment]
辛苦大佬了

**Comment by kingcos** [comment]
WWDC 2019 日文版字幕也已提供，欢迎移步 [Release 页面](https://github.com/kingcos/WWDCHelper/releases)查看、下载、试用。

如有问题，欢迎再提 Issue，感谢各位关注！
