### ISSUE TITLE
pull最新的master代码安装之后提示不支持2019

### ISSUE THREAD

**Issue by iT-Boyer** [kingcos/WWDCHelper#22]
master 5312e3f
```
2019 hasn't been supported currently. Now support WWDC 2012 ~ WWDC 2018 same as developer official website.
```

**Comment by kingcos** [comment]
@huos3203 感谢使用并提出问题哈！

我刚才 Review 了下代码，发现之前将测试代码提交了上去，所以导致参数无效，永远都是获取 2019 年日语的 808 Session。但并不会有 `2019 hasn't been supported currently.` 这样的提示呀，我现在已经将更新的代码 Push，且测试可以正常获取到 2019 年 Session 的信息（`swift build` 后执行 `.build/debug/WWDCHelper -y 2019`），您可以提供下当时的命令吗？😊
