### ISSUE TITLE
使用疑惑

### ISSUE THREAD

**Issue by JiaDingYi** [kingcos/WWDCHelper#3]
按照Readme安装，执行wwdchelper 。
本地没有下载全部wwdc文件。
![snip20170911_4](https://user-images.githubusercontent.com/14258352/30262091-0d8d37a6-9702-11e7-84d4-17e93f151451.png)
只有这几个session，并且只有.md文件

**Comment by kingcos** [comment]
首先感谢您使用并提出 Issue。
执行 `wwdchelper` 不带参数是默认输出所有 Session 的信息。
您若想下载所有 Session 的字幕，可以在后面加上 `-l chs` 参数下载简体中文字幕，抑或 `-l eng` 下载英文字幕，您可以参照 Demo 中最后一个。不推荐的原因是下载文件为 136 个，可能较为耗时。
WWDC 的视频和 PDF 暂未提供直接下载，仅提供了下载地址，原因是觉得命令行下载大文件可能并非极其强烈的需求。
欢迎您再尝试，有问题可以继续问我，如果可以解决也可以关闭 Issue，再次感谢您的使用！

**Comment by JiaDingYi** [comment]
看来是我理解错了，谢谢解答。
