### ISSUE TITLE
Fall 2017的中文字幕已经放出，希望作者已经尽快抓取

### ISSUE THREAD

**Issue by Danie1s** [kingcos/WWDCHelper#7]
万分感谢！！

**Comment by kingcos** [comment]
你好，Issue 收到，首先非常感谢你对这个小项目的关注和使用！
Fall 2017 的简体中文字幕预计会在今天（171018）白天更新，稍后即会发布在 Release 页面。
更新完毕也会在这里再次评论通知你。
再次感谢！🙏

**Comment by kingcos** [comment]
你好，Fall 2017 简体中文字幕已经打包完毕！
可以在 [Releases 页面](https://github.com/kingcos/WWDCHelper/releases)查看、下载。
再次感谢你的支持！如果字幕可以使用，可以关闭该 Issue^ ^。

**Comment by Danie1s** [comment]
谢谢！
